# -*- coding: utf-8 -*-
"""Scrape.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AxkXTp05tjm1SDADoi3RSNMnGbgNF3yf
"""

import csv, requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://www.amazon.in/s?rh=n%3A6612025031&fs=true&ref=lp_6612025031_sar"
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
    "Accept-Language": "en-US,en;q=0.9",
}

response = requests.get(url, headers=headers)

soup = BeautifulSoup(response.content, 'html.parser')

products=[]

for product in soup.find_all("div", class_="s-result-item"):
  name = product.find("span", class_="a-size-medium").text if product.find("span", class_="a-size-medium") else "N/A"
  price = product.find("span", class_="a-price-whole").text if product.find("span", class_="a-price-whole") else "N/A"
  rating = product.find("span", class_="a-icon-alt").text if product.find("span", class_="a-icon-alt") else "N/A"
  seller = product.find("span", class_="a-size-base-plus").text if product.find("span", class_="a-size-base-plus") else "N/A"

  products.append([name, price, rating,seller])

df = pd.DataFrame(products, columns=["Product-Name", "Price", "Rating", "Seller"])
df.to_csv("Scrape.csv", index=False, encoding="utf-8")

import pandas as pd

df = pd.read_csv("Scrape.csv")
df